#!/bin/bash
#
#
#


ROOTPATH=/home/tnan/procurve
SWITCHPATH=$ROOTPATH/switches
CONFIGS=$ROOTPATH/configs
RECIPIENTS=somebody@somecompany.com


USERNAME=username
PASSWORD=password

DATETIME=$(date +%Y-%m-%d-%H:%M:%S)


email-diff () {

    SWITCH=$1
    LOG=$CONFIGS/$SWITCH/$SWITCH.log
    REPORTEDCHANGES=$CONFIGS/$SWITCH/$SWITCH-reported-changes.log
    cat $LOG | mail -s "PROCURVE WATCH: $SWITCH was modified." $RECIPIENTS
    echo "Changes for $DATETIME -----------" >> $REPORTEDCHANGES
    cat $LOG >> $REPORTEDCHANGES 
}

diff-config () {

    SWITCH=$1
    LOGDIR=$CONFIGS/$SWITCH
    NEWCONFIG=$LOGDIR/$SWITCH-$DATETIME.cfg
    OLDCONFIG=$LOGDIR/$SWITCH-LATEST.cfg
    LOG=$LOGDIR/$SWITCH.log

    diff -c10 $OLDCONFIG $NEWCONFIG > $LOG
    DIFFER=$?
    rm $OLDCONFIG
    ln -s $NEWCONFIG $OLDCONFIG

    if [ $DIFFER == 1 ] 
    then
        cp $LOG $LOG-$DATETIME.changed
        email-diff $SWITCH
    fi
}

fetch-config () {

    SWITCH=$1
    LOGDIR=$CONFIGS/$SWITCH

    if [ ! -e $LOGDIR ]
    then
        mkdir $CONFIGS/$SWITCH
    fi

    sshpass -p"$PASSWORD" scp $USERNAME@$SWITCH:cfg/running-config $LOGDIR/$SWITCH-$DATETIME.cfg
    diff-config $SWITCH
}

echo "Start"
for x in `cat $SWITCHPATH/*.txt`
do
    echo "Fetching config for switch $x..."
    fetch-config $x &
    
done
echo "Finished."








