#!/bin/bash
#

ROOTPATH=$(dirname $0)
SETTINGS=$ROOTPATH/etc/procurve-watch.conf

SWITCHPATH=$ROOTPATH/switches
CONFIGSPATH=$ROOTPATH/configs

DATETIME=$(date +%Y-%m-%d-%H:%M:%S)

if [ -e "$SETTINGS" ]
then
    . $SETTINGS
else
    echo "File $SETTINGS missing."
    exit 1
fi

for x in $SWITCHPATH $CONFIGSPATH
do
    if [ ! -e $x ]
    then
        mkdir $x
    fi
done

email-diff () {

    SWITCH=$1
    SWITCHCONFIG_OUTPUTDIR=$2

    LOG=$SWITCHCONFIG_OUTPUTDIR/$SWITCH.log
    REPORTEDCHANGES=$LOG/$SWITCH-reported-changes.log
    cat $LOG | mail -s "PROCURVE WATCH: $SWITCH configuration was modified." $RECIPIENTS
    echo "Changes for $DATETIME -----------" >> $REPORTEDCHANGES
    cat $LOG >> $REPORTEDCHANGES 
}

diff-switch-config () {

    SWITCH=$1
    SWITCHCONFIG_OUTPUTDIR=$2

    LOGDIR=$SWITCHCONFIG_OUTPUTDIR
    NEWCONFIG_FILENAME=$SWITCH-$DATETIME.cfg
    NEWCONFIG=$LOGDIR/$NEWCONFIG_FILENAME
    OLDCONFIG=$LOGDIR/$SWITCH-LATEST.cfg
    LOG=$LOGDIR/$SWITCH.log

    if [ -e $OLDCONFIG ]
    then

        diff -c10 $OLDCONFIG $NEWCONFIG > $LOG
        DIFFER=$?

        if [ $DIFFER == 1 ] 
        then
            cp $LOG $LOG-$DATETIME.changed
            email-diff $SWITCH $LOGDIR
            rm $OLDCONFIG
            ln -s $NEWCONFIG_FILENAME $OLDCONFIG
        else
            rm $NEWCONFIG
        fi
    else
        rm $OLDCONFIG
        ln -s $NEWCONFIG_FILENAME $OLDCONFIG
    fi
}

fetch-config () {

    SWITCH=$1
    SWITCHCONFIG_OUTPUTDIR=$2

    LOGDIR=$SWITCHCONFIG_OUTPUTDIR
    ERRORLOG=$LOGDIR/error-log.txt

    if [ ! -e $LOGDIR ]
    then
        mkdir $LOGDIR
    fi


    if [ $USESSHKEYS == "No" ]
    then
        sshpass -p"$PASSWORD" scp $USERNAME@$SWITCH:cfg/running-config $LOGDIR/$SWITCH-$DATETIME.cfg >> $ERRORLOG 2>&1
    elif [ $USESSHKEYS == "Yes" ]
    then
        scp $USERNAME@$SWITCH:cfg/running-config $LOGDIR/$SWITCH-$DATETIME.cfg >> $ERRORLOG 2>&1
    fi
    diff-switch-config $SWITCH $SWITCHCONFIG_OUTPUTDIR >> $ERRORLOG 2>&1
}


process_list_of_switches () {
    
    FILE_LISTOFSWITCHES=$1
    GROUPCONFIG_OUTPUTDIR=$CONFIGSPATH/${FILE_LISTOFSWITCHES#$SWITCHPATH}
    mkdir -p $GROUPCONFIG_OUTPUTDIR

    SWITCHES=$(cat $FILE_LISTOFSWITCHES)

    COUNTER=0
    for switch in $SWITCHES
    do
        if [ -z $switch ]
        then
            continue
        fi

        SWITCHCONFIG_OUTPUTDIR=$GROUPCONFIG_OUTPUTDIR/$switch
        if [[ ! -e $SWITCHCONFIG_OUTPUTDIR ]]
        then
            mkdir -p $SWITCHCONFIG_OUTPUTDIR
        fi

        echo "Fetching config for switch $switch..."
        fetch-config $switch $SWITCHCONFIG_OUTPUTDIR &

        ((COUNTER++))
        STATE=$(expr $COUNTER % $PARALLEL)
        if [ $STATE == 0 ]
        then
            sleep $COOLDOWN
        fi
    done
}

echo "Start $DATETIME ---------------------------------"

FILES=$(find $SWITCHPATH -type f)
for x in $FILES
do
    echo "Processing config file $x"
    process_list_of_switches $x
done

echo "Finished."








